# Generated by Django 5.0.2 on 2024-03-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblowingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportTitle', models.CharField(max_length=255)),
                ('reportText', models.TextField()),
                ('reportPDF', models.FileField(upload_to='report_pdf/')),
                ('reportJPEG', models.ImageField(upload_to='report_image/')),
            ],
        ),
    ]
