# Generated by Django 5.0.2 on 2024-03-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblowingapp', '0002_report'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='report',
        #     name='reportText',
        #     field=models.FileField(upload_to='report_txt/'),
        # ),
    ]
