# Generated by Django 5.0.2 on 2024-03-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblowingapp', '0003_alter_report_reporttext'),
        ('whistleblowingapp', '0003_remove_report_attachment_remove_report_description_and_more'),
    ]

    operations = [
    ]
