# Generated by Django 5.0.2 on 2024-03-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblowingapp', '0005_report_admin_notes_report_reportjpeg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reportTitle',
            field=models.CharField(default='', max_length=255),
        ),  
    ]
