# Generated by Django 5.0.2 on 2024-03-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblowingapp', '0006_report_reportjpeg_report_reportpdf_report_reporttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reportJPEG',
            field=models.ImageField(blank=True, null=True, upload_to='report_image/'),
        ),
        migrations.AddField(
            model_name='report',
            name='reportPDF',
            field=models.FileField(blank=True, null=True, upload_to='report_pdf/'),
        ),
        migrations.AddField(
            model_name='report',
            name='reportText',
            field=models.FileField(blank=True, null=True, upload_to='report_txt/'),
        ),
    ]
